default_install_hook_types: [pre-commit,prepare-commit-msg]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: prepare-commit-msg
        name: prepare-commit-msg
        entry: ./hooks/story
        stages: [prepare-commit-msg]
        language: script
        verbose: true
