#!/usr/bin/env sh

STORYNUMBER=$1

if [ -z "$STORYNUMBER" ]; then
    read -p "Please enter the Jira story reference e.g. TI-234: " STORYNUMBER

    if [ -z "$STORYNUMBER" ]; then
        echo "no story number provided"
        exit 1
    fi
fi

if [ -d "$XDG_CONFIG_HOME" ]; then
    echo "$STORYNUMBER" > "$XDG_CONFIG_HOME/.story-number"
else
    mkdir -p "$HOME/.config"
    echo "$STORYNUMBER" > "$HOME/.config/.story-number"
fi
