#!/usr/bin/env sh

COMMAND=$1

if [ -z "$COMMAND" ]; then
    echo "Usage: git story <command|story-ref> "
    echo ""
    echo "Set the story ref"
    echo "\t git story TEAM-123"
    echo ""
    echo "Commands available:"
    echo "\tclear: clears existing story reference"
    echo "\tshow: show current story ref"
    exit 1
fi


if [ $COMMAND = "clear" ]; then
    rm "${XDG_CONFIG_HOME:-$HOME/.config}/.story-number" 2&>/dev/null
    exit 0
fi

if [ $COMMAND = "show" ]; then
    if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/.story-number" ]; then
        STORYNUMBER=$(cat "${XDG_CONFIG_HOME:-$HOME/.config}/.story-number")
        echo ""
        echo "Current story ref: $STORYNUMBER"
    else
        echo ""
        echo "No story ref set"
    fi
    exit 0
fi

STORYNUMBER=$1

if [ -d "$XDG_CONFIG_HOME" ]; then
    echo "$STORYNUMBER" > "$XDG_CONFIG_HOME/.story-number"
else
    mkdir -p "$HOME/.config"
    echo "$STORYNUMBER" > "$HOME/.config/.story-number"
fi
