#!/usr/bin/env sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/.story-number" ]; then
    STORYNUMBER=$(cat "${XDG_CONFIG_HOME:-$HOME/.config}/.story-number")
fi

if [ -z "$STORYNUMBER" ]; then
    echo "warning: no jira ref found; maybe you forgot to do 'git story'?"
else
    git interpret-trailers --in-place --trailer "jira: $STORYNUMBER" "$COMMIT_MSG_FILE"
    if test -z "$COMMIT_SOURCE"; then
        /usr/bin/perl -i.bak -pe 'print "\n" if !$first_line++' "$COMMIT_MSG_FILE"
    fi
fi
